### PR TITLE
Test PR

### PR DESCRIPTION
**Pull request by Redeem-Grimm-Satoshi**
Verify CircleCI Build

### CODE REVIEW

**Comment by Redeem-Grimm-Satoshi** [comment]
@nuilewis Great but why is your CircleCI not spawning? had to initialize automatically

**Comment by Redeem-Grimm-Satoshi** [comment]
I did a compile time error to fail the build test

**Comment by nuilewis** [comment]
> @nuilewis Great but why is your CircleCI not spawning? had to initialize automatically

Hi @Redeem-Grimm-Satoshi, that's odd, because I just spun up a new branch and did a test PR, and it seems to work. I will look into it.
image

**Comment by nuilewis** [comment]
> > @nuilewis Great but why is your CircleCI not spawning? had to initialize automatically
> 
> Hi @Redeem-Grimm-Satoshi, that's odd, because I just spun up a new branch and did a test PR, and it seems to work. I will look into it. image

I think I found the issue. I left this toggle off
image

**Comment by nuilewis** [comment]
> > > @nuilewis Great but why is your CircleCI not spawning? had to initialize automatically
> > 
> > 
> > Hi @Redeem-Grimm-Satoshi, that's odd, because I just spun up a new branch and did a test PR, and it seems to work. I will look into it. image
> 
> I think I found the issue. I left this toggle off image

I think we can try again and see if it works. thank you!

**Pull request closed without merging**
